# Generated by Django 4.2.17 on 2024-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgetest',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgetest',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
